app = 'ayam-chat-api'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[env]
  PORT = "3000"
  NODE_ENV = "production"

[checks]
  [checks.alive]
    type = "http"
    port = 3000
    method = "GET"
    path = "/health"
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
